"""
Django settings for inventory_master project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import warnings

# Подавляем предупреждение django-fsm о переходе на viewflow
warnings.filterwarnings('ignore', message='.*django-fsm.*')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'user.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3)79-7^5@ww@79xk2s&koc4_tb4ay)r$4#+)qja@mp37(0hm-w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "samvet.imaster.uz",
    "admin-samvet.imaster.uz",
    "scan-samvet.imaster.uz",
    "imaster.kerek.uz",
    "www.imaster.kerek.uz",
    "samvet.kerek.uz",
    "127.0.0.1",
    "localhost",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup',
    'django_filters',

    'rest_framework',  # добавляем rest framework для API
    'rest_framework_simplejwt',
    'corsheaders',
    'user',
    'university',
    'inventory',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


CORS_ALLOWED_ORIGINS = [
    "https://demo.kerek.uz",
    "https://inventor-new.vercel.app",
    "https://admin.kerek.uz",
    "http://localhost:3000",
    "http://localhost:5173",
    "https://inventor-admin.vercel.app",
    "https://samvet.imaster.uz",
    "https://admin-samvet.imaster.uz",
    "https://scan-samvet.imaster.uz",
    "https://imaster.kerek.uz",
    "https://samvet.kerek.uz",
]

CORS_ALLOW_CREDENTIALS = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'cache-control',
    'pragma',
]

CSRF_TRUSTED_ORIGINS = [
    "https://demo.kerek.uz",
    "https://inventor-new.vercel.app",
    "https://admin.kerek.uz",
    "http://localhost:3000",
    "http://localhost:5173",
    "https://inventor-admin.vercel.app",
    "https://samvet.imaster.uz",
    "https://admin-samvet.imaster.uz",
    "https://scan-samvet.imaster.uz",
    "https://imaster.kerek.uz",
    "https://samvet.kerek.uz",
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15 MB

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'EXCEPTION_HANDLER': 'inventory_master.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'inventory.pagination.StandardPagination',
    'PAGE_SIZE': 20,
}

ROOT_URLCONF = 'inventory_master.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_master.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Для разработки используем SQLite, для продакшена — PostgreSQL
USE_POSTGRES = os.environ.get('USE_POSTGRES', 'False') == 'True'

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'inventory_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # Connection pooling — держим соединение 10 минут
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Database Cache (используем БД вместо Redis — экономим RAM)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = '/admin/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Путь к папке с твоими статическими файлами
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Время жизни access токена (например, 1 час)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Время жизни refresh токена (например, 7 дней)
    'ROTATE_REFRESH_TOKENS': False,  # Не поворачиваем refresh токены
    'BLACKLIST_AFTER_ROTATION': False,  # Не блокируем старые токены после поворота
    'ALGORITHM': 'HS256',  # Алгоритм подписи (обычно это HS256)
    'SIGNING_KEY': 'your-secret-key',  # Твой секретный ключ для подписи
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
